/**
DO NOT EDIT THIS FILE
*/

package clients

import (
	"fmt"
	"log"
	"math/rand"
	"os"
)

type EmailClient struct {
	file *os.File
}

func NewEmailClient() *EmailClient {
	file, err := os.OpenFile("files/output/notified_emails.txt", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}

	return &EmailClient{file: file}
}

func (c *EmailClient) Send(email string, message string) error {
	if rand.Float64() < 0.005 {
		return fmt.Errorf("unknown error")
	}

	c.file.WriteString(email + "\n")

	return nil
}
