/**
DO NOT EDIT THIS FILE
*/

package clients

import (
	"fmt"
	"log"
	"math/rand"
	"os"
)

type SmsClient struct {
	file *os.File
}

func NewSmsClient() *SmsClient {
	file, err := os.OpenFile("files/output/notified_phone_numbers.txt", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}

	return &SmsClient{file: file}
}

func (c *SmsClient) Send(phoneNumber string, message string) error {
	if rand.Float64() < 0.005 {
		return fmt.Errorf("unknown error")
	}

	c.file.WriteString(phoneNumber + "\n")

	return nil
}
